import { makeStyles, shorthands, tokens } from '@fluentui/react-components';

export const useAuthFormStyles = makeStyles({
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    marginBottom: '12px',
  },
  label: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#334155', // Slate 700 - very dark grey/blue for high contrast
  },
  fieldError: {
    fontSize: '12px',
    color: tokens.colorPaletteRedForeground1,
  },
  errorBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '6px 10px',
    borderRadius: '6px',
    backgroundColor: tokens.colorPaletteRedBackground1,
    fontSize: '12px',
    color: tokens.colorPaletteRedForeground1,
  },
  errorIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '18px',
    height: '18px',
    borderRadius: '50%',
    backgroundColor: tokens.colorPaletteRedForeground1,
    color: '#fff',
    fontWeight: 700,
    fontSize: '11px',
    flexShrink: 0,
  },
  inputWrapper: {
    display: 'flex',
    alignItems: 'center',
    position: 'relative',
  },
  visibilityBtn: {
    position: 'absolute',
    right: '4px',
  },
  forgotRow: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginBottom: '16px',
  },
  forgotLink: {
    fontSize: '13px',
    color: tokens.colorBrandForegroundLink,
    textDecoration: 'none',
    ':hover': { textDecoration: 'underline' },
  },
  submitRow: {
    marginTop: '8px',
    marginBottom: '8px',
  },
  divider: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    fontSize: '13px',
    color: tokens.colorNeutralForeground4,
    margin: '12px 0',
  },
  socialRow: {
    display: 'flex',
    justifyContent: 'center',
    gap: '12px',
  },
  phoneRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  phonePrefix: {
    fontSize: '14px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground3,
    padding: '0 4px',
  },
  otpChannelRow: {
    marginTop: '4px',
  },
  passwordFieldsError: {
    border: `1px solid ${tokens.colorPaletteRedBorder1}`,
    borderRadius: '8px',
    padding: '12px',
  },
});

export const usePageStyles = makeStyles({
  verifyWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
    padding: '24px',
    backgroundColor: tokens.colorNeutralBackground2,
  },
  verifyCard: {
    width: '100%',
    maxWidth: '420px',
    padding: '40px 32px',
    textAlign: 'center' as const,
    borderRadius: '16px',
    boxShadow: tokens.shadow16,
  },
  verifyHeading: {
    margin: '0 0 8px 0',
  },
  verifySubheading: {
    fontSize: '14px',
    color: tokens.colorNeutralForeground3,
    margin: '0 0 24px 0',
  },
  verifyForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    textAlign: 'left' as const,
  },
  verifyInputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  verifyError: {
    fontSize: '12px',
    color: tokens.colorPaletteRedForeground1,
  },
  verifyBackLinks: {
    marginTop: '20px',
    fontSize: '13px',
    display: 'flex',
    justifyContent: 'center',
    gap: '8px',
    color: tokens.colorNeutralForeground4,
  },
  verifyBackLink: {
    color: tokens.colorBrandForegroundLink,
    textDecoration: 'none',
    ':hover': { textDecoration: 'underline' },
  },
  accountWrapper: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    flex: 1,
    width: '100%',
    padding: '64px 32px 80px',
    background: 'transparent',
    '@media (max-width: 640px)': { padding: '40px 16px 56px' },
  },
  accountCard: {
    width: '100%',
    maxWidth: '480px',
    padding: '40px 32px',
    borderRadius: '16px',
    boxShadow: tokens.shadow16,
  },
  accountHeading: {
    margin: '0 0 24px 0',
  },
  accountDl: {
    display: 'grid',
    gridTemplateColumns: 'auto 1fr',
    gap: '8px 20px',
    fontSize: '14px',
    marginBottom: '24px',
    '& dt': { fontWeight: 600, color: tokens.colorNeutralForeground3 },
    '& dd': { margin: 0, color: tokens.colorNeutralForeground1 },
  },
  profileLayout: {
    width: '100%',
    maxWidth: '1080px',
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
    gap: '24px',
    '@media (max-width: 760px)': { gridTemplateColumns: '1fr' },
  },
  profileCard: {
    position: 'relative',
    overflow: 'hidden',
    padding: '32px',
    borderRadius: '20px',
    background: 'rgba(15, 23, 42, 0.64)',
    backdropFilter: 'blur(20px) saturate(150%)',
    WebkitBackdropFilter: 'blur(20px) saturate(150%)',
    border: '1px solid rgba(255, 255, 255, 0.07)',
    boxShadow: '0 12px 40px rgba(0, 0, 0, 0.24), 0 1px 0 rgba(255, 255, 255, 0.04) inset',
    '& .fui-Input': {
      backgroundColor: 'rgba(96, 165, 250, 0.08)',
      ...shorthands.borderColor('rgba(148, 163, 184, 0.34)'),
      borderRadius: '8px',
      transition: 'background-color 0.2s ease, border-color 0.2s ease, box-shadow 0.2s ease',
      '&:hover': {
        backgroundColor: 'rgba(96, 165, 250, 0.12)',
        ...shorthands.borderColor('rgba(147, 197, 253, 0.58)'),
      },
      '&:focus-within': {
        backgroundColor: 'rgba(96, 165, 250, 0.14)',
        ...shorthands.borderColor('#60a5fa'),
        boxShadow: '0 0 0 1px rgba(96, 165, 250, 0.35)',
      },
    },
    '& .fui-Input input': {
      backgroundColor: 'transparent',
    },
    '::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: '12%',
      right: '12%',
      height: '1px',
      background: 'linear-gradient(90deg, transparent, rgba(96, 165, 250, 0.8), rgba(52, 211, 153, 0.55), transparent)',
    },
    '@media (max-width: 640px)': { padding: '24px 20px' },
  },
  profileHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '16px',
    marginBottom: '28px',
    paddingBottom: '20px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
  },
  profileIdentity: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  profileAvatar: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: '48px',
    height: '48px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #3b82f6, #8b5cf6)',
    color: '#fff',
    fontSize: '15px',
    fontWeight: 800,
    boxShadow: '0 6px 18px rgba(59, 130, 246, 0.26)',
  },
  profileEyebrow: {
    display: 'block',
    color: '#60a5fa',
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.1em',
    textTransform: 'uppercase' as const,
    marginBottom: '3px',
  },
  profileMuted: {
    color: 'rgba(226, 232, 240, 0.5)',
    fontSize: '14px',
    margin: '4px 0 0',
  },
  profileForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    marginBottom: '28px',
  },
  profileGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
    '@media (max-width: 480px)': { gridTemplateColumns: '1fr' },
  },
  profileField: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
    fontSize: '12px',
    fontWeight: 600,
    color: 'rgba(226, 232, 240, 0.72)',
    letterSpacing: '0.02em',
  },
  contactInputRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    width: '100%',
    '& > :first-child': { flex: 1 },
    '& > *': { flexShrink: 0 },
  },
  profileSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    '& h3': { margin: 0, fontSize: '18px', fontWeight: 700, color: 'rgba(248, 250, 252, 0.94)' },
    '& p': { margin: 0 },
  },
  profileSummary: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '16px',
    marginBottom: '24px',
    '& strong, & span': { display: 'block' },
    '& strong': { fontSize: '22px', color: 'rgba(248, 250, 252, 0.96)' },
    '& span': { color: 'rgba(226, 232, 240, 0.5)', fontSize: '13px', marginTop: '5px' },
  },
  preferenceRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    fontWeight: 400,
  },
  verificationRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    padding: '12px 0',
    borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
  },
  otpForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    width: '100%',
    marginTop: '4px',
    '& > :first-child': { width: '100%' },
    '& > :last-child': { alignSelf: 'flex-start' },
  },
  addressTypeRow: {
    display: 'flex',
    gap: '8px',
  },
  addressForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  addressGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '10px',
    '@media (max-width: 480px)': { gridTemplateColumns: '1fr' },
  },
  addressRow: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '12px',
    padding: '14px 0',
    borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
    '& strong': { fontSize: '13px', textTransform: 'capitalize' as const },
    '& p': { color: tokens.colorNeutralForeground3, fontSize: '13px', marginTop: '4px' },
  },
  addressActions: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '6px',
    marginTop: '8px',
  },
});

export const INDIA_PREFIX = '+91';
